#!/usr/bin/env python3

import argparse
import difflib
import hashlib
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[3]
GALP_ROOT = REPO_ROOT / "galp"
CODEGEN_DIR = GALP_ROOT / "scripts" / "codegen"
OWNERSHIP_MARKER = ".galp-codegen-owned"

GENERATED_BINDINGS_MANIFEST = json.loads(
    (CODEGEN_DIR / "generated_bindings_manifest.json").read_text()
)
if GENERATED_BINDINGS_MANIFEST.get("schema") != "galp-generated-bindings-v1":
    raise RuntimeError("unsupported generated binding manifest")
EXPECTED_BINDING_FILES = GENERATED_BINDINGS_MANIFEST["bindings"]
EXPECTED_HEADER_FILES = GENERATED_BINDINGS_MANIFEST["headers"]


def relative_files(root: Path, suffix: str) -> list[str]:
    return sorted(str(path.relative_to(root)) for path in root.rglob(f"*{suffix}") if path.is_file())


def content_hashes(root: Path, paths: list[str]) -> dict[str, str]:
    return {path: hashlib.sha256((root / path).read_bytes()).hexdigest() for path in paths}


def print_list_diff(label: str, expected: list[str], generated: list[str]) -> bool:
    if expected == generated:
        return False
    print(f"{label} generated file list differs from expected manifest", file=sys.stderr)
    for line in difflib.unified_diff(
        expected,
        generated,
        fromfile=f"expected {label}",
        tofile=f"generated {label}",
        lineterm="",
    ):
        print(line, file=sys.stderr)
    return True


def run_codegen(tmp_dir: Path) -> tuple[Path, Path]:
    bindings_dir = tmp_dir / "bindings"
    headers_dir = tmp_dir / "include" / "galp_bench" / "generated"
    bindings_dir.mkdir(parents=True, exist_ok=True)
    headers_dir.mkdir(parents=True, exist_ok=True)

    subprocess.run(
        [
            sys.executable,
            str(CODEGEN_DIR / "generate_kernel_bindings.py"),
            "--out-dir",
            str(bindings_dir),
            "--header-out-dir",
            str(headers_dir),
            "--logging-level",
            "40",
        ],
        check=True,
        cwd=REPO_ROOT,
    )
    return bindings_dir, headers_dir


def check(tmp_dir: Path) -> int:
    first_bindings_dir, first_headers_dir = run_codegen(tmp_dir / "first")
    second_bindings_dir, second_headers_dir = run_codegen(tmp_dir / "second")

    generated_cu = relative_files(first_bindings_dir, ".cu")
    generated_cuh = relative_files(first_headers_dir, ".cuh")

    failed = False
    failed |= print_list_diff(".cu", sorted(EXPECTED_BINDING_FILES), generated_cu)
    failed |= print_list_diff(".cuh", sorted(EXPECTED_HEADER_FILES), generated_cuh)
    failed |= print_list_diff("second .cu", generated_cu, relative_files(second_bindings_dir, ".cu"))
    failed |= print_list_diff("second .cuh", generated_cuh, relative_files(second_headers_dir, ".cuh"))
    if content_hashes(first_bindings_dir, generated_cu) != content_hashes(second_bindings_dir, generated_cu):
        failed = True
        print("generated .cu contents are not reproducible", file=sys.stderr)
    if content_hashes(first_headers_dir, generated_cuh) != content_hashes(second_headers_dir, generated_cuh):
        failed = True
        print("generated .cuh contents are not reproducible", file=sys.stderr)

    dictshfl32 = [name for name in generated_cu if name.startswith("dictshfl32-")]
    if dictshfl32:
        failed = True
        print("dictshfl32 bindings are generated by default:", file=sys.stderr)
        for name in dictshfl32:
            print(f"  {name}", file=sys.stderr)

    if failed:
        print(f"generated output does not match the expected manifest; temporary output: {tmp_dir}", file=sys.stderr)
        return 1

    print("generated output matches the expected manifest")
    return 0


def create_owned_tmp_dir(path: Path) -> Path:
    tmp_dir = path.resolve()
    if tmp_dir.exists():
        raise ValueError(f"--tmp-dir must not already exist: {tmp_dir}")
    tmp_dir.mkdir()
    (tmp_dir / OWNERSHIP_MARKER).write_text("owned by check_generated_reproducible.py\n")
    return tmp_dir


def remove_owned_tmp_dir(tmp_dir: Path) -> None:
    marker = tmp_dir / OWNERSHIP_MARKER
    if not marker.is_file():
        raise RuntimeError(f"refusing to remove unowned temporary directory: {tmp_dir}")
    shutil.rmtree(tmp_dir)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--tmp-dir",
        help="Create and use this new temporary directory; an existing path is always rejected.",
    )
    parser.add_argument("--keep-tmp", action="store_true", help="Keep the generated temporary output.")
    args = parser.parse_args(argv)

    if args.tmp_dir:
        try:
            tmp_dir = create_owned_tmp_dir(Path(args.tmp_dir))
        except (OSError, ValueError) as error:
            parser.error(str(error))
        try:
            return check(tmp_dir)
        finally:
            if args.keep_tmp:
                print(f"kept temporary output: {tmp_dir}")
            else:
                remove_owned_tmp_dir(tmp_dir)

    tmp_dir = Path(tempfile.mkdtemp(prefix="galp_codegen_check_"))
    try:
        return check(tmp_dir)
    finally:
        if args.keep_tmp:
            print(f"kept temporary output: {tmp_dir}")
        else:
            shutil.rmtree(tmp_dir, ignore_errors=True)


if __name__ == "__main__":
    raise SystemExit(main())
